---
- name: reload systemd configuration
  systemd: daemon_reload=yes

- name: restart cloud-sql-proxy
  service: name=cloud-sql-proxy state=restarted

- name: restart pythonapp
  action: supervisorctl name=pythonapp state=restarted

- name: add pythonapp
  supervisorctl: name=pythonapp state=present

- name: start pythonapp
  supervisorctl: name=pythonapp state=restarted