---
- hosts: local
  connection: local
  gather_facts: no
  vars:
    PROJECT_ID: "{{ lookup('env', 'PROJECT_ID') }}"
    region: "{ { lookup('env', 'region') } }"
    zone: "{{ lookup('env', 'zone') }}"
    DATA_BACKEND: "{ { lookup('env', 'DATA_BACKEND') } }"
    CLOUD_STORAGE_BUCKET: "{{ lookup('env', 'CLOUD_STORAGE_BUCKET') }}"
    CLOUDSQL_USER: "{ { lookup('env', 'CLOUDSQL_USER') } }"
    CLOUDSQL_PASSWORD: "{{ lookup('env', 'CLOUDSQL_PASSWORD') }}"
    CLOUDSQL_DATABASE: "{ { lookup('env', 'CLOUDSQL_DATABASE') } }"
    CLOUDSQL_CONNECTION_NAME: "{ { lookup('env', 'CLOUDSQL_CONNECTION_NAME') } }"

  tasks:
    - name: Download fluentd installer
      get_url:
        url: "https://storage.googleapis.com/signals-agents/logging/google-fluentd-install.sh"
        dest: "/tmp/google-fluentd-install.sh"
        mode: 0755

    - name: Execute the fluentd-installer.sh
      shell: /tmp/google-fluentd-install.sh

    - name: Remove the fluentd-installer.sh
      file:
       path: "/tmp/google-fluentd-install.sh"
       state: "absent"

    - name: Install cloud-sql-proxy
      get_url:
        url: "https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64"
        dest: "/usr/local/bin/cloud-sql-proxy"
        mode: 0755

    - name: Configure cloud-sql-proxy service
      template:
        src: cloud-sql-proxy.service
        dest: /etc/systemd/system/cloud-sql-proxy.service
        owner: root
        group: root
        mode: 0644
      notify:
        - reload systemd configuration
        - restart cloud-sql-proxy

    - name: Enable cloud-sql-proxy service
      service:
        name: cloud-sql-proxy.service
        enabled: true